title: Data Science Tutorials
author: Hunter Lybbert
logo: _static/favicon.png

execute:
  execute_notebooks: off

repository:
  url: https://github.com/hunter-lybbert/tutorials
  branch: main

html:
  favicon: _static/favicon.png
  extra_css:
    - custom.css
  theme_options:
    use_repository_button: true

# Add the Sphinx block right here at the bottom
sphinx:
  config:
    templates_path: ["_templates"]
    html_sidebars:
      "**": ["navbar-logo.html", "sbt-sidebar-nav.html"]